### ISSUE TITLE
Images Missing in Edit Mode

### ISSUE THREAD

**Issue by jmason03** [timbuckingham/bigtree-media-gallery-field-type#3]
When I upload a photo it is processed correctly and there doesn't seem to be any issues. However, when I go back in to edit that item, the photo does not appear (the "Currently:" and the photo both are not there). Somewhere between the photo finishing being processed and then the field being drawn for the edit dialog box, this value $field["options"]["image"] is disappearing. So ultimately I can't update the item without re-uploading the photo because it thinks the value is blank.

Is this something you experience as well?

**Comment by timbuckingham** [comment]
This should be fixed in the latest release, thanks for finding the bug -- I got sidelined after implementing this but you caught it before the two clients that are using it! Commit is here: https://github.com/timbuckingham/bigtree-media-gallery-field-type/commit/796f51369518e97251b92b81cc37349555a58e88
